include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120

analyzer:
  errors:
    todo: info

linter:
  rules:
    omit_obvious_local_variable_types: true
    omit_obvious_property_types: true
