name: Flutter Checks

on:
  workflow_dispatch:
  pull_request:

jobs:
  check_formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.9'
          channel: stable
          cache: true
      - name: Disable analytics
        run: flutter config --no-analytics
      - name: Flutter pub get
        run: flutter pub get
      - name: Check Dart formatting
        run: dart format --line-length 120 --output=none --set-exit-if-changed lib test

  analyze:
    name: Analyze Dart
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.9'
          channel: stable
          cache: true
      - name: Disable analytics
        run: flutter config --no-analytics
      - name: Flutter pub get
        run: flutter pub get
      - name: Run Dart analyze
        run: dart analyze --fatal-infos

  test:
    name: Flutter test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.9'
          channel: stable
          cache: true
      - name: Disable analytics
        run: flutter config --no-analytics
      - name: Flutter pub get
        run: flutter pub get
      - name: Flutter test
        run: flutter test --coverage
